### ISSUE TITLE
Ban lasts longer than it's supposed to, doesn't show in mod-log

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#820]
@bakape Seems to be an issue in upkeep.go.
Did this
![image](https://user-images.githubusercontent.com/30435868/43512091-beeafad8-953f-11e8-9af6-4807e18c9771.png)
Am banned only on /a/, doesn't show the white screen, regular thread with the alert saying "You are banned from this board".
bans/a doesn't show me banned, and there's nothing in the mod-log, I checked /all/ too.

**Comment by Chiiruno** [comment]
I should mention it's been well past a minute, thus why I think the problem is somehow upkeep didn't clean up the ban too, but did clean up the mod-log/bans

**Comment by bakape** [comment]
Well fuck. I will debug this later this evening.

**Comment by Chiiruno** [comment]
Likely has something to do with the command spam fucking something up.
Could you restart the server so I don't have to change my IP please?

**Comment by bakape** [comment]
Restarted.

**Comment by Chiiruno** [comment]
Thanks!

**Comment by bakape** [comment]
Should have been fixed with 552334e3cf27aba33f3f77693df5ce63526dbcd8

**Comment by Chiiruno** [comment]
@bakape Unfortunately, it's not fixed yet. Did the same thing and am now having the same problem.
p-please restart the server ;_;

**Comment by Chiiruno** [comment]
Oh, this is interesting. If I go to the thread directly with images.meguca.org, I am unbanned.

**Comment by Chiiruno** [comment]
It also unbans me with the regular site. Weird.
Keeping open since this is still a bug, but now we know how to force synchronize.

**Comment by Chiiruno** [comment]
Unless I did that right as upkeep updated something. I'm not sure.

**Comment by Chiiruno** [comment]
Yeah, unless is was the half or hour task, there's no way it could have been the minute task, since I did the test well past 2 minutes.

**Comment by bakape** [comment]
Maybe system bans are somehow not propagated properly.  Needs investigation.

**Comment by bakape** [comment]
Solved problem in NGINX config. Check now.

**Comment by Chiiruno** [comment]
My IP shows as IPv6 now on the ban thing.
Was that the reason?

**Comment by Chiiruno** [comment]
Also it got lifted.
