### ISSUE TITLE
Infinite captcha per-IP

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#978]
Not sure why this happens, seems to work with TOR after a few service restarts, doesn't seem localStorage or cookie-based.
Also, on another note, here's a non-shit-ass encode of happi flens: https://files.catbox.moe/qy268r.webm

**Comment by bakape** [comment]
>Not sure why this happens

The reason is the captcha being sent from one IP and the websocket connection using another.

>Also, on another note, here's a non-shit-ass encode of happi flens: https://files.catbox.moe/qy268r.webm

That better be 2 pass VP9.

**Comment by Chiiruno** [comment]
Strange, because it works if I go back to my normal IP after loading with TOR and completing a captcha.
However, fresh load, I get infinite captcha with my own IP.

>That better be 2 pass VP9.

Of course.

**Comment by bakape** [comment]
Check which IPs the websocket connections and the POST requests are on.

**Comment by Chiiruno** [comment]
Is it possible that cloudflare is doing something different for websocket connections and POST requests?
I know for a fact my IP doesn't change.

**Comment by bakape** [comment]
Actually, yes. We probably need to include an optional `websocket_ip` field
in the captcha and set that with JS to equal the websocket ip ... except
that means you can now auth 2 IPs with one captcha.

**Comment by Chiiruno** [comment]
If there's not a better way, authorizing 2 IPs with one captcha is worth it.
Usability is important.

**Comment by bakape** [comment]
Can you do this, if I land the dockerised testing today?

**Comment by Chiiruno** [comment]
I made some edits to my above post, you may want to view from the website.

**Comment by bakape** [comment]
>The part I'm having a hard time modeling in my head is whether the server sends the captcha with the websocket_ip field, or if the client fills that out to the server.

Put a hidden `websocket_ip` field on the form and set it's value using JS.  Do it from the client-side JS side. I'd prefer to not introduce meguca specifics to capthcouli. 

>If the client is filling that out, then that's a security risk because you could mod your client to submit any IP, or straight up use websockets/POST to do that.

Still a security risk, even if added automatically. That's why I did not want it added. 

>We need to have the server ensure that the websocket IP and the POST IP is the same I think, and the way to do that is to change the websocket IP server-side if different, to match the POST IP.

Some kind of session token? This is getting complicated. 

>As well as that, to change the websocket IP client-side

Requires reconnection.

**Comment by Chiiruno** [comment]
I don't want to submit a PR that ends up with shit tons of spam from our Australian friend, so maybe some kind of session token would be better?
Yeah, session token -> reconnect if different IP client-side.
I can do this, but it might take me a little while since this is new territory for me.

**Comment by bakape** [comment]
Forcing a reconnect is bad. You will have to store connected sessions in the DB. Actually, do this. It's good for security. Once board pages are also connected, we can even ensure only connected clients can use the other POSt APIs. See https://github.com/bakape/meguca/blob/master/server/src/meguca/websockets/websockets.go#L101-L105 You should generate a random token and write it into the DB and then remove it inside of defer just like with IP registration. 
Table should be `(ip inet, token bytea, created_on timestamp default now())`. Clear this table on non-imager-only server start for dirty start cleanup. Token should be 64 bit base64. 

Thoughts or additions?

**Comment by Chiiruno** [comment]
I'll respond to this in a moment, but can you ban the frogposting faggot real quick?

**Comment by Chiiruno** [comment]
Everything there you said should work, I'll see if implementation is any different.
I'll get to this later tonight, I have some things to do this morning.

**Comment by bakape** [comment]
Could be caused by university or corporate proxies with IP pools and no binding.

**Comment by bakape** [comment]
Possibly fixed by  112b207c84fc75cc86c636a65cafd04052c3d273

**Comment by bakape** [comment]
- [ ] Bind captchas to session cookie instead of IP
- [ ] Read session cookie, if exists, on websocket connection. 
  - [ ] If none, generate new token and send to client for setting
  - [ ] Persist cookie on Client struct
- [ ] Read cookie on captcha submission

**Comment by Chiiruno** [comment]
Just got an infinite captcha that refreshing, opening new tab, etc doesn't seem to fix.
Happened after trying to upload image then immediately spoilering after finishing captcha, of course, the image did not upload, and the post did not register.

**Comment by Chiiruno** [comment]
The usual method of typing something in a new post and filling captcha is not working either.
on a side note, a great way to troll banned users would be silently banning and making them have infinite captcha instead of a you are banned thingy.

**Comment by Chiiruno** [comment]
Posting with TOR or a proxy works, but main IP doesn't.
Anyway, things work again, wakarimasenlol.

**Comment by Chiiruno** [comment]
I haven't had this in quite a while, so gonna close.

**Comment by bakape** [comment]
That's because we are off CF again. This is still an issue.

**Comment by Chiiruno** [comment]
Fucking cloudflare.
